In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split


In [2]:
df = pd.read_excel('Dethi_data.xlsx')

In [3]:
df

order   limit clear drop delete  remove  c1  c2  c3  c4  ...     d4  \
0          1   20000     y    c      b      24   2   2  -1  -1  ...      0   
1          2  120000     y    c      c      26  -1   2   0   0  ...   3272   
2          3   90000     y    c      c      34   0   0   0   0  ...  14331   
3          4   50000     y    c      b      37   0   0   0   0  ...  28314   
4          5   50000     x    c      b      57  -1   0  -1   0  ...  20940   
...      ...     ...   ...  ...    ...     ...  ..  ..  ..  ..  ...    ...   
29995  29996  220000     x    d      b      39   0   0   0   0  ...  88004   
29996  29997  150000     x    d      c      43  -1  -1  -1  -1  ...   8979   
29997  29998   30000     x    c      c      37   4   3   2  -1  ...  20878   
29998  29999   80000     x    d      b      41   1  -1   0   0  ...  52774   
29999  30000   50000     x    c      b      46   0   0   0   0  ...  36535   

          d5     d6     f1     f2     f3    f4     f5    f6  default  
0          0      0      0    689      0     0      0     0        1  
1       3455   3261      0   1000   1000  1000      0  2000        1  
2      14948  15549   1518   1500   1000  1000   1000  5000        0  
3      28959  29547   2000   2019   1200  1100   1069  1000        0  
4      19146  19131   2000  36681  10000  9000    689   679        0  
...      ...    ...    ...    ...    ...   ...    ...   ...      ...  
29995  31237  15980   8500  20000   5003  3047   5000  1000        0  
29996   5190      0   1837   3526   8998   129      0     0        0  
29997  20582  19357      0      0  22000  4200   2000  3100        1  
29998  11855  48944  85900   3409   1178  1926  52964  1804        1  
29999  32428  15313   2078   1800   1430  1000   1000  1000        1  

[30000 rows x 25 columns]

CÂU 1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   order    30000 non-null  int64 
 1   limit    30000 non-null  int64 
 2   clear    30000 non-null  object
 3   drop     30000 non-null  object
 4   delete   30000 non-null  object
 5   remove   30000 non-null  int64 
 6   c1       30000 non-null  int64 
 7   c2       30000 non-null  int64 
 8   c3       30000 non-null  int64 
 9   c4       30000 non-null  int64 
 10  c5       30000 non-null  int64 
 11  c6       30000 non-null  int64 
 12  d1       30000 non-null  int64 
 13  d2       30000 non-null  int64 
 14  d3       30000 non-null  int64 
 15  d4       30000 non-null  int64 
 16  d5       30000 non-null  int64 
 17  d6       30000 non-null  int64 
 18  f1       30000 non-null  int64 
 19  f2       30000 non-null  int64 
 20  f3       30000 non-null  int64 
 21  f4       30000 non-null  int64 
 22

In [5]:
df.describe()

order           limit        remove            c1            c2  \
count  30000.000000    30000.000000  30000.000000  30000.000000  30000.000000   
mean   15000.500000   167484.322667     35.485500     -0.016700     -0.133767   
std     8660.398374   129747.661567      9.217904      1.123802      1.197186   
min        1.000000    10000.000000     21.000000     -2.000000     -2.000000   
25%     7500.750000    50000.000000     28.000000     -1.000000     -1.000000   
50%    15000.500000   140000.000000     34.000000      0.000000      0.000000   
75%    22500.250000   240000.000000     41.000000      0.000000      0.000000   
max    30000.000000  1000000.000000     79.000000      8.000000      8.000000   

                 c3            c4            c5            c6             d1  \
count  30000.000000  30000.000000  30000.000000  30000.000000   30000.000000   
mean      -0.166200     -0.220667     -0.266200     -0.291100   51223.330900   
std        1.196868      1.169139      1.133187      1.149988   73635.860576   
min       -2.000000     -2.000000     -2.000000     -2.000000 -165580.000000   
25%       -1.000000     -1.000000     -1.000000     -1.000000    3558.750000   
50%        0.000000      0.000000      0.000000      0.000000   22381.500000   
75%        0.000000      0.000000      0.000000      0.000000   67091.000000   
max        8.000000      8.000000      8.000000      8.000000  964511.000000   

       ...             d4             d5             d6             f1  \
count  ...   30000.000000   30000.000000   30000.000000   30000.000000   
mean   ...   43262.948967   40311.400967   38871.760400    5663.580500   
std    ...   64332.856134   60797.155770   59554.107537   16563.280354   
min    ... -170000.000000  -81334.000000 -339603.000000       0.000000   
25%    ...    2326.750000    1763.000000    1256.000000    1000.000000   
50%    ...   19052.000000   18104.500000   17071.000000    2100.000000   
75%    ...   54506.000000   50190.500000   49198.250000    5006.000000   
max    ...  891586.000000  927171.000000  961664.000000  873552.000000   

                 f2            f3             f4             f5  \
count  3.000000e+04   30000.00000   30000.000000   30000.000000   
mean   5.921163e+03    5225.68150    4826.076867    4799.387633   
std    2.304087e+04   17606.96147   15666.159744   15278.305679   
min    0.000000e+00       0.00000       0.000000       0.000000   
25%    8.330000e+02     390.00000     296.000000     252.500000   
50%    2.009000e+03    1800.00000    1500.000000    1500.000000   
75%    5.000000e+03    4505.00000    4013.250000    4031.500000   
max    1.684259e+06  896040.00000  621000.000000  426529.000000   

                  f6       default  
count   30000.000000  30000.000000  
mean     5215.502567      0.221200  
std     17777.465775      0.415062  
min         0.000000      0.000000  
25%       117.750000      0.000000  
50%      1500.000000      0.000000  
75%      4000.000000      0.000000  
max    528666.000000      1.000000  

[8 rows x 22 columns]

In [6]:
df.shape

(30000, 25)

CÂU 2:

In [7]:
df_train, df_test = train_test_split(df, test_size = 0.1, random_state=10)

In [8]:
df_train.shape

(27000, 25)

In [9]:
df_test.shape

(3000, 25)

CÂU 3:

In [10]:
def check_l_in_df(l, df):
    for n in l:
        if n not in df:
            return False
    return True

In [11]:
check_l_in_df([2664, 1392, 18817, 485, 26435] ,df_test.order)

False

CÂU 4:

In [12]:
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.linear_model import LinearRegression

In [13]:
MLR = LinearRegression()
MLR.fit(df_train[['c1','d1','f1','c2','d2','f2','f3','f4','f5','f6']].values,df_train['limit'].values)
y_MLR_pred = MLR.predict(df_test[['c1','d1','f1','c2','d2','f2','f3','f4','f5','f6']].values)
mae_MLR = mean_absolute_error(df_test['limit'].values, y_MLR_pred)
r2_MLR = r2_score(df_test['limit'].values, y_MLR_pred)
print("MAE of MLR: ", mae_MLR)
print("R2 of MLR: ", r2_MLR)


MAE of MLR:  82906.8479776912
R2 of MLR:  0.3003500023931771


CÂU 5:

In [14]:
MLR.predict([[-1.0, 9640.0,15134.0,-2.0,7404.0, 0.0, 7002.0, 8167.0,3996.0,2000.0]])

array([213447.42417051])

BUILD Hybrid Model:

In [15]:
from sklearn.neighbors import KNeighborsClassifier
KNN = KNeighborsClassifier(n_neighbors=20)
KNN.fit(df_train[['c1','d1','f1']].values,df_train['drop'].values)

KNeighborsClassifier(n_neighbors=20)

In [16]:
from sklearn.naive_bayes import GaussianNB
GNB = GaussianNB()
GNB.fit(df_train[['c2','d2','f2']].values, df_train['delete'].values)


GaussianNB()

CÂU 6:

In [17]:
from sklearn.metrics import accuracy_score
y_KNN_pred_train = KNN.predict(df_train[['c1','d1','f1']].values)
acc_KNN_train = accuracy_score(df_train['drop'].values, y_KNN_pred_train)
print("Accuracy of KNN on train set: ", acc_KNN_train)

Accuracy of KNN on train set:  0.5292962962962963


CÂU 7:

In [18]:
def find_max(a):
    max_num = -1
    for num in a:
        if num > max_num:
            max_num = num
    return max_num


In [19]:
KNN.predict_proba(df_train[['c1','d1','f1']].values)

array([[0.  , 0.3 , 0.55, ..., 0.  , 0.  , 0.  ],
       [0.  , 0.4 , 0.4 , ..., 0.  , 0.  , 0.  ],
       [0.  , 0.2 , 0.6 , ..., 0.  , 0.  , 0.  ],
       ...,
       [0.  , 0.2 , 0.55, ..., 0.  , 0.  , 0.  ],
       [0.  , 0.15, 0.65, ..., 0.  , 0.  , 0.  ],
       [0.  , 0.25, 0.6 , ..., 0.  , 0.  , 0.  ]], shape=(27000, 7))

In [20]:
knn_features = pd.DataFrame(KNN.predict_proba(df_train[['c1','d1','f1']].values)).apply(find_max, axis=1)
gnb_feature = pd.DataFrame(GNB.predict_proba(df_train[['c2','d2','f2']].values)).apply(find_max,axis = 1)

In [21]:
gnb_feature

0        0.616622
1        0.610136
2        0.615249
3        0.608126
4        0.611553
           ...   
26995    0.610108
26996    0.612436
26997    0.610388
26998    0.605027
26999    0.615483
Length: 27000, dtype: float64

In [22]:
knn_features

0        0.55
1        0.40
2        0.60
3        0.55
4        0.45
         ... 
26995    0.60
26996    0.60
26997    0.55
26998    0.65
26999    0.60
Length: 27000, dtype: float64

In [23]:
GNB.predict_proba(df_train[['c2','d2','f2']].values)

array([[0.00617813, 0.37281647, 0.61662224, 0.00438316],
       [0.01588524, 0.36977095, 0.61013647, 0.00420734],
       [0.0065499 , 0.37424329, 0.61524904, 0.00395777],
       ...,
       [0.0184313 , 0.36691163, 0.61038763, 0.00426943],
       [0.01553456, 0.37541887, 0.60502666, 0.0040199 ],
       [0.00933826, 0.37108414, 0.61548254, 0.00409506]], shape=(27000, 4))

In [24]:
np.mean(knn_features)

np.float64(0.5371074074074075)

In [25]:
knn_features.isnull().sum()

np.int64(0)

CÂU 8:

In [26]:
X_train = df_train[['c1','d1','f1','c2','d2','f2','f3','f4','f5','f6']].values

In [27]:
X_train = pd.DataFrame(X_train, columns=['c1','d1','f1','c2','d2','f2','f3','f4','f5','f6'])

In [28]:
X_train

c1     d1    f1  c2     d2     f2     f3      f4      f5    f6
0       0  60005  3000   0  41223  10000   3000    5000   15000     0
1      -1   1560  1000   0   1280    590   1168    1582  145564  5069
2       0  82235  3000   0  67757   3000    182  123000    2740  2200
3      -1   2491  1709  -1   1709    574    556    2306    2562  2111
4       0  30153  2000   0  28384   2000   2552    2000    3000  8000
...    ..    ...   ...  ..    ...    ...    ...     ...     ...   ...
26995   0  30589  2239  -1   2225   3700  20739   10003   40115  8756
26996   0  44664  4110   0  48028      0   4600    1000    2000     0
26997   0   9457  1107   0   9554   1310   2000     269    1000  1100
26998  -2    390  4780  -2   1780      0      0       0       0     0
26999  -1  61687  3500   0  59130   3300   6000    5000    2000  3000

[27000 rows x 10 columns]

In [29]:
X_train['knn_feature'] = knn_features

In [30]:
X_train['gnb_feature'] = gnb_feature

In [31]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27000 entries, 0 to 26999
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   c1           27000 non-null  int64  
 1   d1           27000 non-null  int64  
 2   f1           27000 non-null  int64  
 3   c2           27000 non-null  int64  
 4   d2           27000 non-null  int64  
 5   f2           27000 non-null  int64  
 6   f3           27000 non-null  int64  
 7   f4           27000 non-null  int64  
 8   f5           27000 non-null  int64  
 9   f6           27000 non-null  int64  
 10  knn_feature  27000 non-null  float64
 11  gnb_feature  27000 non-null  float64
dtypes: float64(2), int64(10)
memory usage: 2.5 MB


In [32]:
X_train.describe().T[['mean','std','min','max']]

mean           std           min         max
c1              -0.018037      1.123907      -2.00000        8.00
d1           51168.963037  73817.042109 -165580.00000   964511.00
f1            5648.137222  16608.006654       0.00000   873552.00
c2              -0.134630      1.198905      -2.00000        8.00
d2           49097.768222  71290.357714  -30000.00000   983931.00
f2            5902.824815  23389.333635       0.00000  1684259.00
f3            5255.438741  17936.668742       0.00000   896040.00
f4            4885.918741  15944.587472       0.00000   621000.00
f5            4841.508593  15448.043585       0.00000   426529.00
f6            5251.629963  17815.088574       0.00000   528666.00
knn_feature      0.537107      0.099185       0.30000        0.95
gnb_feature      0.609517      0.044243       0.49554        1.00

In [33]:
X_train.var()

c1             1.263166e+00
d1             5.448956e+09
f1             2.758259e+08
c2             1.437373e+00
d2             5.082315e+09
f2             5.470609e+08
f3             3.217241e+08
f4             2.542299e+08
f5             2.386421e+08
f6             3.173774e+08
knn_feature    9.837664e-03
gnb_feature    1.957414e-03
dtype: float64

In [34]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=2, include_bias=True )
poly.fit(X_train.values)
X_train_poly = poly.fit_transform(X_train.values)

In [35]:
HybridModel = LinearRegression()
HybridModel.fit(X_train_poly, df_train['limit'].values)

LinearRegression()

In [36]:
X_test = df_test[['c1','d1','f1','c2','d2','f2','f3','f4','f5','f6']].values

In [37]:
X_test = pd.DataFrame(X_test, columns=['c1','d1','f1','c2','d2','f2','f3','f4','f5','f6'])

In [38]:
knn_feature_test = pd.DataFrame(KNN.predict_proba(df_test[['c1','d1','f1']].values)).apply(find_max, axis=1)
gnb_feature_test = pd.DataFrame(GNB.predict_proba(df_test[['c2','d2','f2']].values)).apply(find_max, axis=1)

In [39]:
X_test['knn_feature'] = knn_feature_test
X_test['gnb_feature'] = gnb_feature_test

In [40]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   c1           3000 non-null   int64  
 1   d1           3000 non-null   int64  
 2   f1           3000 non-null   int64  
 3   c2           3000 non-null   int64  
 4   d2           3000 non-null   int64  
 5   f2           3000 non-null   int64  
 6   f3           3000 non-null   int64  
 7   f4           3000 non-null   int64  
 8   f5           3000 non-null   int64  
 9   f6           3000 non-null   int64  
 10  knn_feature  3000 non-null   float64
 11  gnb_feature  3000 non-null   float64
dtypes: float64(2), int64(10)
memory usage: 281.4 KB


In [41]:
X_test_poly = poly.fit_transform(X_test.values)

In [42]:
y_pred_hybrid = HybridModel.predict(X_test_poly)

In [43]:
MLR_mae = mean_absolute_error(df_test['limit'].values, MLR.predict(df_test[['c1','d1','f1','c2','d2','f2','f3','f4','f5','f6']].values))
Hybrid_mae = mean_absolute_error(df_test['limit'].values, y_pred_hybrid)
print("MAE of MLR on test set: ", MLR_mae)
print("MAE of Hybrid Model on test set: ", Hybrid_mae)

MAE of MLR on test set:  82906.8479776912
MAE of Hybrid Model on test set:  77391.4555915978


In [44]:
MLR_r2 = r2_score(df_test['limit'].values, MLR.predict(df_test[['c1','d1','f1','c2','d2','f2','f3','f4','f5','f6']].values))
Hybrid_r2 = r2_score(df_test['limit'].values, y_pred_hybrid)
print("R2 of MLR on test set: ", MLR_r2)
print("R2 of Hybrid Model on test set: ", Hybrid_r2)

R2 of MLR on test set:  0.3003500023931771
R2 of Hybrid Model on test set:  0.3605198432973561


In [45]:

sample = [[-1.0,9640.0, 15134.0, -2.0, 7404.0, 0.0, 7002.0, 8167.0, 3996.0, 2000.0]]

In [46]:
KNN_feature_sample = KNN.predict_proba([[-1.0,9640.0, 15134.0]])
GNB_feature_sample = GNB.predict_proba([[-2.0, 7404.0, 0.0]])

In [47]:
KNN_feature_sample

array([[0.  , 0.65, 0.3 , 0.05, 0.  , 0.  , 0.  ]])

In [48]:
KNN_feature_sample = find_max(KNN_feature_sample[0])
GNB_feature_sample = find_max(GNB_feature_sample[0])


In [49]:
sample[0].append(KNN_feature_sample)
sample[0].append(GNB_feature_sample)

In [50]:
HybridModel.predict(poly.fit_transform(sample))

array([242099.09451776])