In [1]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

In [2]:
#Giai đoạn 1
df = pd.read_excel('Dethi_data.xlsx')

In [3]:
#MLR giai đoạn 1
X_1 = ['c1', 'd1', 'f1', 'c2', 'd2', 'f2', 'f3', 'f4', 'f5', 'f6']
y_1 = ['limit']

In [4]:
from sklearn.model_selection import train_test_split
df_train, df_test = train_test_split(df, test_size=0.1, random_state=10)

In [5]:
df_train

order   limit clear drop delete  remove  c1  c2  c3  c4  ...     d4  \
2663    2664  180000     x    c      b      46   0   0   0   0  ...  50016   
1391    1392  170000     y    b      c      30  -1   0  -1  -1  ...   1168   
18816  18817  420000     y    c      c      29   0   0   0   0  ...  -8318   
484      485  100000     y    c      b      43  -1  -1  -1  -1  ...    556   
26434  26435  300000     y    b      b      36   0   0   0   0  ...  22554   
...      ...     ...   ...  ...    ...     ...  ..  ..  ..  ..  ...    ...   
28017  28018  240000     y    c      c      27   0  -1   0  -1  ...  20694   
17728  17729   50000     y    c      b      51   0   0   2   2  ...  50484   
29199  29200   10000     x    c      c      27   0   0   0   0  ...   9025   
7293    7294  100000     y    c      b      27  -2  -2  -2  -2  ...      0   
17673  17674  320000     y    c      c      35  -1   0   0   0  ...  22337   

          d5      d6    f1     f2     f3      f4      f5    f6  default  
2663   45956   52926  3000  10000   3000    5000   15000     0        0  
1391    2160  145564  1000    590   1168    1582  145564  5069        0  
18816  96795   81523  3000   3000    182  123000    2740  2200        0  
484     2306    2562  1709    574    556    2306    2562  2111        0  
26434  11858   13838  2000   2000   2552    2000    3000  8000        0  
...      ...     ...   ...    ...    ...     ...     ...   ...      ...  
28017  19771   38603  2239   3700  20739   10003   40115  8756        0  
17728  50404   50241  4110      0   4600    1000    2000     0        0  
29199   7886    8382  1107   1310   2000     269    1000  1100        0  
7293       0       0  4780      0      0       0       0     0        0  
17673  23358   13536  3500   3300   6000    5000    2000  3000        0  

[27000 rows x 25 columns]

In [6]:
X_train_1 = df_train[X_1].copy()
y_train_1 = df_train[y_1].copy()
X_test_1 = df_test[X_1].copy()
y_test_1 = df_test[y_1].copy()

In [7]:
from sklearn.linear_model import LinearRegression
MLR1 = LinearRegression()

In [8]:
MLR1.fit(X_train_1.values,y_train_1.values)

LinearRegression()

In [9]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score
mae1 = mean_absolute_error(y_test_1, MLR1.predict(X_test_1))
r21 = r2_score(y_test_1, MLR1.predict(X_test_1))
print(mae1)
print(r21)

82906.8479776912
0.3003500023931771


c:\Users\Hoang Nghi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
c:\Users\Hoang Nghi\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


In [10]:
#Câu 1
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   order    30000 non-null  int64 
 1   limit    30000 non-null  int64 
 2   clear    30000 non-null  object
 3   drop     30000 non-null  object
 4   delete   30000 non-null  object
 5   remove   30000 non-null  int64 
 6   c1       30000 non-null  int64 
 7   c2       30000 non-null  int64 
 8   c3       30000 non-null  int64 
 9   c4       30000 non-null  int64 
 10  c5       30000 non-null  int64 
 11  c6       30000 non-null  int64 
 12  d1       30000 non-null  int64 
 13  d2       30000 non-null  int64 
 14  d3       30000 non-null  int64 
 15  d4       30000 non-null  int64 
 16  d5       30000 non-null  int64 
 17  d6       30000 non-null  int64 
 18  f1       30000 non-null  int64 
 19  f2       30000 non-null  int64 
 20  f3       30000 non-null  int64 
 21  f4       30000 non-null  int64 
 22

In [11]:
#Câu 2
df_train.shape

(27000, 25)

In [12]:
df_test.shape

(3000, 25)

In [13]:
def find_list_in_order(l, order):
    for num in l:
        if num not in order:
            return False
    return True

In [14]:
#Câu 3
a = [2664,1392,18817,485,26435]
b = [20413,1297,3907,20455,5201]
d = [24449,4368,5750,13544,5330]
e = [28018,17729,29200,7294,17674]



In [15]:
find_list_in_order(a, df_train.order.values)

True

In [16]:
#Câu 4
print(mae1)
print(r21)

82906.8479776912
0.3003500023931771


In [17]:
#Câu 5
input = [-1.0,9640.0,15134.0,-2.0,7404.0,0.0,7002.0,8167.0,3996.0,2000.0]
print(MLR1.predict([input]))

[[213447.42417051]]


In [18]:
KNN_X_train = df_train[['c1', 'd1', 'f1']].copy()
KNN_y_train = df_train['drop'].copy()
KNN_X_test = df_test[['c1','d1','f1']].copy()
KNN_y_test = df_test['drop'].copy()

In [19]:
#Câu 6
from sklearn.metrics import accuracy_score


KNN1 = KNeighborsClassifier(n_neighbors=20)
KNN1.fit(KNN_X_train.values, KNN_y_train.values)
KNN1_y_pred = KNN1.predict(KNN_X_train.values)
print(accuracy_score(KNN_y_train, KNN1_y_pred))

0.5292962962962963


In [20]:
#Câu 7
knn_feature = KNN1.predict_proba(KNN_X_train.values).max(axis=1)

In [21]:
round(np.mean(knn_feature),2)

np.float64(0.54)

In [22]:
GNB = GaussianNB()

GNB_X_train = df_train[['c2','d2','f2']].copy()
GNB_y_train = df_train['delete'].copy()
GNB_X_test = df_test[['c2','d2','f2']].copy()
GNB_y_test = df_test['delete'].copy()

GNB.fit(GNB_X_train.values, GNB_y_train.values)
gnb_feature = GNB.predict_proba(GNB_X_train.values).max(axis=1)

In [23]:
gnb_feature

array([0.61662224, 0.61013647, 0.61524904, ..., 0.61038763, 0.60502666,
       0.61548254], shape=(27000,))

In [24]:
X_train_2 = pd.DataFrame({'knn_feature':knn_feature,
                         'gnb_feature':gnb_feature,
                           'f3': df_train.f3.values,
                             'f4': df_train.f4.values,
                             'f5': df_train.f5.values,
                             'f6': df_train.f6.values})

y_train_2 = df_train['limit']
X_test_2 = pd.DataFrame({'knn_feature':KNN1.predict_proba(KNN_X_test.values).max(axis=1),
                         'gnb_feature':GNB.predict_proba(GNB_X_test.values).max(axis=1),
                           'f3': df_test.f3.values,
                             'f4': df_test.f4.values,
                             'f5': df_test.f5.values,
                             'f6': df_test.f6.values})


y_test_2 = df_test['limit']

In [25]:
#Câu 8
arr = X_train_2.values.astype(float)
print("Min:", np.min(arr))
print("Mean:", np.mean(arr))
print("Var:", np.var(arr))
print("Max:", np.max(arr))
print("-------------------------------------------------")

Min: 0.0
Mean: 3372.6071102407514
Var: 194366041.855579
Max: 896040.0
-------------------------------------------------


In [26]:
from sklearn.preprocessing import PolynomialFeatures
Poly = PolynomialFeatures(degree=2, include_bias=True)
X_train_2 = Poly.fit_transform(X_train_2.values)
X_test_2 = Poly.transform(X_test_2.values)

In [27]:
#Câu 9:
MLR2 = LinearRegression()

MLR2.fit(X_train_2,y_train_2)
MLR2_y_pred = MLR2.predict(X_test_2)

mae2 = mean_absolute_error(y_test_2, MLR2_y_pred)
r22 = r2_score(y_test_2, MLR2_y_pred)

print(f'mae1: {mae1}')
print(f'mae2: {mae2}')
print('---------------------')
print(f'r21: {r21}')
print(f'r22: {r22}')
# a. MAE của hybrid là 82906.8479776912 -> sai
# b. Mô hình Hybrid và MLR tương đương nhau ->  sai
# c. R-squared của hybrid là 0.5747749190894 -> sai
# d. Sai số MAE trên Hybrid nhỏ hơn MLR -> sai
# e. Mô hình MLR tốt hơn -> đúng
# f. R-Squared của Hybrid là 0.36049 -> sai
# g. Sai số đánh giá của MAE trên mô hình Hybrid lớn hơn MLR -> đúng
# h. MAE cảu hybrid là 6063.2127933 -> sai


mae1: 82906.8479776912
mae2: 91741.51316526326
---------------------
r21: 0.3003500023931771
r22: 0.1923314139271739


In [28]:
knn = KNN1.predict_proba([[-1.0,9640.0,15134.0]]).max()
gnb = GNB.predict_proba([[-2.0,7404.0,0.0]]).max()
new_input = [knn, gnb, 7002.0, 8167.0,3996.0,2000.0]
new_input = Poly.transform([new_input])
MLR2.predict(new_input)

array([163225.11442906])

In [31]:
MLR2.coef_

array([-2.40811519e+00,  4.21522569e+04, -3.65805050e+06,  1.18546995e+00,
        1.55263619e+00,  1.89983848e+00,  1.30602410e+00, -1.28012639e+05,
        5.48617871e+04,  2.02883162e-01,  9.50181770e-01, -1.95966394e-01,
       -1.13383058e-01,  2.58693836e+06,  1.23039921e-02, -5.52593174e-01,
        3.15015343e-01,  9.90134493e-01, -1.36907948e-06,  1.51260970e-06,
       -1.42776669e-06, -2.70131168e-06, -3.42320789e-06, -3.94787852e-06,
       -4.29797952e-06, -4.49728252e-06, -2.85368100e-06, -4.44200698e-06])

In [ ]:
pip install matplotlib
pip install numpy
pip install pandas
pip install seaborn
pip install scikit-learn==1.4.2
