In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pass: 1234560

In [5]:
data = pd.read_excel('Dethi_data.xlsx')

In [6]:
data

order   limit clear drop delete  remove  c1  c2  c3  c4  ...     d4  \
0          1   20000     y    c      b      24   2   2  -1  -1  ...      0   
1          2  120000     y    c      c      26  -1   2   0   0  ...   3272   
2          3   90000     y    c      c      34   0   0   0   0  ...  14331   
3          4   50000     y    c      b      37   0   0   0   0  ...  28314   
4          5   50000     x    c      b      57  -1   0  -1   0  ...  20940   
...      ...     ...   ...  ...    ...     ...  ..  ..  ..  ..  ...    ...   
29995  29996  220000     x    d      b      39   0   0   0   0  ...  88004   
29996  29997  150000     x    d      c      43  -1  -1  -1  -1  ...   8979   
29997  29998   30000     x    c      c      37   4   3   2  -1  ...  20878   
29998  29999   80000     x    d      b      41   1  -1   0   0  ...  52774   
29999  30000   50000     x    c      b      46   0   0   0   0  ...  36535   

          d5     d6     f1     f2     f3    f4     f5    f6  default  
0          0      0      0    689      0     0      0     0        1  
1       3455   3261      0   1000   1000  1000      0  2000        1  
2      14948  15549   1518   1500   1000  1000   1000  5000        0  
3      28959  29547   2000   2019   1200  1100   1069  1000        0  
4      19146  19131   2000  36681  10000  9000    689   679        0  
...      ...    ...    ...    ...    ...   ...    ...   ...      ...  
29995  31237  15980   8500  20000   5003  3047   5000  1000        0  
29996   5190      0   1837   3526   8998   129      0     0        0  
29997  20582  19357      0      0  22000  4200   2000  3100        1  
29998  11855  48944  85900   3409   1178  1926  52964  1804        1  
29999  32428  15313   2078   1800   1430  1000   1000  1000        1  

[30000 rows x 25 columns]

In [ ]:
from sklearn.model_selection import train_test_split
X = data[['c1','d1','f1','c2','d2','f2','f3','f4','f5','f6']].values
y = data['limit']


0         20000
1        120000
2         90000
3         50000
4         50000
          ...  
29995    220000
29996    150000
29997     30000
29998     80000
29999     50000
Name: limit, Length: 30000, dtype: int64

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state= 10)

In [22]:
y_train

2663     180000
1391     170000
18816    420000
484      100000
26434    300000
          ...  
28017    240000
17728     50000
29199     10000
7293     100000
17673    320000
Name: limit, Length: 27000, dtype: int64

In [23]:
from sklearn.linear_model import LinearRegression

In [25]:
LNR = LinearRegression()
LNR.fit(X_train,y_train)

LinearRegression()

In [57]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import root_mean_squared_error
from sklearn.metrics import r2_score

In [27]:
y_test_pred = LNR.predict(X_test)

In [28]:
mean_absolute_error(y_test,y_test_pred)

82906.8479776907

In [29]:
root_mean_squared_error(y_test, y_test_pred)

106063.21290029172

In [58]:
r2_score(y_test, y_test_pred)

0.30035000239325105

In [43]:

def test_in_df(l, y):
    for num in l:
        if num not in y:
            return False
    return True

test_in_df([24449, 4368, 5750, 13544, 5330], y_train)

False

In [44]:
LNR.predict([[-1.0,9640.0,15134.0,-2.0,7404.0,0.0,7002.0,8167.0,3996.0,2000.0]])

array([213447.42417045])

In [45]:
from sklearn.neighbors import KNeighborsClassifier

In [46]:
KNN = KNeighborsClassifier(n_neighbors=20)
KNN.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=20)

In [48]:
KNN.score()

TypeError: KNeighborsClassifier.score() missing 2 required positional arguments: 'X' and 'y'

In [49]:
X_train

array([[     0,  60005,   3000, ...,   5000,  15000,      0],
       [    -1,   1560,   1000, ...,   1582, 145564,   5069],
       [     0,  82235,   3000, ..., 123000,   2740,   2200],
       ...,
       [     0,   9457,   1107, ...,    269,   1000,   1100],
       [    -2,    390,   4780, ...,      0,      0,      0],
       [    -1,  61687,   3500, ...,   5000,   2000,   3000]],
      shape=(27000, 10))

In [51]:
y_test

20412    160000
1296      50000
3906     380000
20454    400000
5200      60000
          ...  
24448    320000
4367      50000
5749     160000
13543    150000
5329     170000
Name: limit, Length: 3000, dtype: int64

In [55]:
data.columns

Index(['order', 'limit', 'clear', 'drop', 'delete', 'remove', 'c1', 'c2', 'c3',
       'c4', 'c5', 'c6', 'd1', 'd2', 'd3', 'd4', 'd5', 'd6', 'f1', 'f2', 'f3',
       'f4', 'f5', 'f6', 'default'],
      dtype='object')

In [56]:
data.isnull().sum()

order      0
limit      0
clear      0
drop       0
delete     0
remove     0
c1         0
c2         0
c3         0
c4         0
c5         0
c6         0
d1         0
d2         0
d3         0
d4         0
d5         0
d6         0
f1         0
f2         0
f3         0
f4         0
f5         0
f6         0
default    0
dtype: int64

In [61]:
from sklearn.metrics import accuracy_score

In [62]:
KNN_train_pred = KNN.predict(X_train)
accuracy_score(y_train, KNN_train_pred)

0.2883703703703704

In [63]:
knn = KNeighborsClassifier(n_neighbors=20)
knn.fit(X_train, y_train)

# Dự đoán trên tập huấn luyện
y_pred_train = knn.predict(X_train)

# Tính độ chính xác
accuracy = accuracy_score(y_train, y_pred_train)
print("Độ chính xác (Accuracy) trên tập huấn luyện:", accuracy)

Độ chính xác (Accuracy) trên tập huấn luyện: 0.2883703703703704


In [64]:
KNN = KNeighborsClassifier(n_neighbors=20)

In [66]:
X_KNN = data[['c1','d1','f1']].values
X_KNN

array([[    2,  3913,     0],
       [   -1,  2682,     0],
       [    0, 29239,  1518],
       ...,
       [    4,  3565,     0],
       [    1, -1645, 85900],
       [    0, 47929,  2078]], shape=(30000, 3))

In [68]:
y_KNN = data['drop'].values
y_KNN

array(['c', 'c', 'c', ..., 'c', 'd', 'c'], shape=(30000,), dtype=object)

In [71]:
X_KNN_train,X_KNN_test, y_KNN_train,  y_KNN_test = train_test_split(X_KNN, y_KNN, test_size=0.1, random_state=10)

In [72]:
KNN.fit(X_KNN_train, y_KNN_train)

KNeighborsClassifier(n_neighbors=20)

In [73]:
y_KNN_train_pred = KNN.predict(X_KNN_train)

In [74]:
accuracy_score(y_KNN_train, y_KNN_train_pred)

0.5292962962962963

In [77]:
df_train, df_test = train_test_split(data, random_state=10, test_size=0.1)

In [92]:
test_in_df([20413, 1297, 3907, 20455, 5201]  ,df_test.order)

False

In [93]:
from sklearn.naive_bayes import GaussianNB
GNB = GaussianNB()

In [94]:
GNB.fit(df_train[['c2','d2','f2']],df_train['delete'])

GaussianNB()

In [113]:
X_test = pd.DataFrame(X_test, columns = ['c1','d1','f1','c2','d2','f2','f3','f4','f5','f6'])

In [114]:
X_test['knn_feature'] = [max(a) for a in KNN.predict_proba(X_KNN_test)]

In [115]:
X_test['gnb_feature'] = [max(a) for a in GNB.predict_proba(df_test[['c2','d2','f2']])]

In [ ]:
GNB.predict_proba(df_train[['c2','d2','f2']])

array([[0.00617813, 0.37281647, 0.61662224, 0.00438316],
       [0.01588524, 0.36977095, 0.61013647, 0.00420734],
       [0.0065499 , 0.37424329, 0.61524904, 0.00395777],
       ...,
       [0.0184313 , 0.36691163, 0.61038763, 0.00426943],
       [0.01553456, 0.37541887, 0.60502666, 0.0040199 ],
       [0.00933826, 0.37108414, 0.61548254, 0.00409506]], shape=(27000, 4))

In [107]:
X_train

c1     d1    f1  c2     d2     f2     f3      f4      f5    f6  \
0       0  60005  3000   0  41223  10000   3000    5000   15000     0   
1      -1   1560  1000   0   1280    590   1168    1582  145564  5069   
2       0  82235  3000   0  67757   3000    182  123000    2740  2200   
3      -1   2491  1709  -1   1709    574    556    2306    2562  2111   
4       0  30153  2000   0  28384   2000   2552    2000    3000  8000   
...    ..    ...   ...  ..    ...    ...    ...     ...     ...   ...   
26995   0  30589  2239  -1   2225   3700  20739   10003   40115  8756   
26996   0  44664  4110   0  48028      0   4600    1000    2000     0   
26997   0   9457  1107   0   9554   1310   2000     269    1000  1100   
26998  -2    390  4780  -2   1780      0      0       0       0     0   
26999  -1  61687  3500   0  59130   3300   6000    5000    2000  3000   

       knn_feature  gnb_feature  
0             0.55     0.616622  
1             0.40     0.610136  
2             0.60     0.615249  
3             0.55     0.608126  
4             0.45     0.611553  
...            ...          ...  
26995         0.60     0.610108  
26996         0.60     0.612436  
26997         0.55     0.610388  
26998         0.65     0.605027  
26999         0.60     0.615483  

[27000 rows x 12 columns]

In [108]:
from sklearn.preprocessing import PolynomialFeatures
Poly = PolynomialFeatures(degree = 2, interaction_only=True, include_bias=True)
Poly.fit_transform(X_train)

array([[ 1.00000000e+00,  0.00000000e+00,  6.00050000e+04, ...,
         0.00000000e+00,  0.00000000e+00,  3.39142232e-01],
       [ 1.00000000e+00, -1.00000000e+00,  1.56000000e+03, ...,
         2.02760000e+03,  3.09278179e+03,  2.44054590e-01],
       [ 1.00000000e+00,  0.00000000e+00,  8.22350000e+04, ...,
         1.32000000e+03,  1.35354790e+03,  3.69149426e-01],
       ...,
       [ 1.00000000e+00,  0.00000000e+00,  9.45700000e+03, ...,
         6.05000000e+02,  6.71426398e+02,  3.35713199e-01],
       [ 1.00000000e+00, -2.00000000e+00,  3.90000000e+02, ...,
         0.00000000e+00,  0.00000000e+00,  3.93267327e-01],
       [ 1.00000000e+00, -1.00000000e+00,  6.16870000e+04, ...,
         1.80000000e+03,  1.84644761e+03,  3.69289523e-01]],
      shape=(27000, 79))

In [116]:
X_test = Poly.fit_transform(X_test)

In [110]:
Hybird = LinearRegression()
Hybird.fit(X_train, y_train)

LinearRegression()

In [118]:
mean_absolute_error(y_train, Hybird.predict(X_train))

79896.19887766046

In [121]:
r2_score(y_train, Hybird.predict(X_train))

0.3433661973763408

In [123]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error
import numpy as np
import pandas as pd
df = data
# =============================
# 1️⃣ Đọc dữ liệu
# =============================
# Giả sử df chứa các cột: f1, f2, f3, f4, f5, f6, limit
# df = pd.read_csv("data.csv")

X = df[['f1','f2','f3','f4','f5','f6']].values
y = df['limit'].values

# Chia tập train/test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=10)

# =============================
# 2️⃣ Trích xuất đặc trưng
# =============================

# --- KNN feature ---
knn = KNeighborsClassifier(n_neighbors=20)
knn.fit(X_train[:, 0:2], y_train)
knn_train_feat = knn.predict_proba(X_train[:, 0:2]).max(axis=1).reshape(-1,1)
knn_test_feat  = knn.predict_proba(X_test[:, 0:2]).max(axis=1).reshape(-1,1)

# --- GaussianNB feature ---
gnb = GaussianNB()
gnb.fit(X_train[:, 1:3], y_train)
gnb_train_feat = gnb.predict_proba(X_train[:, 1:3]).max(axis=1).reshape(-1,1)
gnb_test_feat  = gnb.predict_proba(X_test[:, 1:3]).max(axis=1).reshape(-1,1)

# --- Giữ nguyên f3–f6 ---
f_train = X_train[:, 2:6]
f_test  = X_test[:, 2:6]

# Gộp thành bộ đặc trưng hybrid
X_train_hybrid = np.hstack([knn_train_feat, gnb_train_feat, f_train])
X_test_hybrid  = np.hstack([knn_test_feat,  gnb_test_feat,  f_test])

# =============================
# 3️⃣ Polynomial Feature Expansion
# =============================
poly = PolynomialFeatures(degree=2, include_bias=True)
X_train_poly = poly.fit_transform(X_train_hybrid)
X_test_poly  = poly.transform(X_test_hybrid)

# =============================
# 4️⃣ Hồi quy tuyến tính
# =============================
mlr = LinearRegression()
mlr.fit(X_train_poly, y_train)

y_pred_train = mlr.predict(X_train_poly)
y_pred_test  = mlr.predict(X_test_poly)

# =============================
# 5️⃣ Đánh giá mô hình
# =============================
r2_train = r2_score(y_train, y_pred_train)
mae_train = mean_absolute_error(y_train, y_pred_train)

r2_test = r2_score(y_test, y_pred_test)
mae_test = mean_absolute_error(y_test, y_pred_test)

print("==== Hybrid Model Evaluation ====")
print(f"R² (Train): {r2_train:.4f}")
print(f"MAE (Train): {mae_train:.4f}")
print(f"R² (Test): {r2_test:.4f}")
print(f"MAE (Test): {mae_test:.4f}")

==== Hybrid Model Evaluation ====
R² (Train): 0.2203
MAE (Train): 90283.5364
R² (Test): 0.2160
MAE (Test): 89066.7718


In [124]:
x_input = np.array([[-1.0, 9640.0, 15134.0, -2.0, 7404.0, 0.0, 7002.0, 8167.0, 3996.0, 2000.0]])

# Trích xuất các feature như pipeline HM
# KNN feature
knn_feature = knn.predict_proba(x_input[:, [0, 1]]).max(axis=1).reshape(-1,1)

# GNB feature
gnb_feature = gnb.predict_proba(x_input[:, [3, 4]]).max(axis=1).reshape(-1,1)

# Giữ nguyên f3–f6
f_features = x_input[:, [6,7,8,9]]

# Kết hợp lại
X_input_hybrid = np.hstack([knn_feature, gnb_feature, f_features])

# Biến đổi Polynomial
X_input_poly = poly.transform(X_input_hybrid)

# Dự báo limit
limit_pred = mlr.predict(X_input_poly)
print("Giá trị dự báo limit:", limit_pred[0])

Giá trị dự báo limit: 200329.83212089824


In [125]:
import numpy as np
import pandas as pd

# Chuyển sang DataFrame cho dễ nhìn
df_hybrid = pd.DataFrame(X_train_hybrid, 
                         columns=['knn_feature', 'gnb_feature', 'f3', 'f4', 'f5', 'f6'])

# Loại bỏ giá trị thiếu (nếu có)
df_hybrid = df_hybrid.dropna()

# Tính toán thống kê mô tả
min_vals = df_hybrid.min()
mean_vals = df_hybrid.mean()
var_vals = df_hybrid.var()
max_vals = df_hybrid.max()

# In kết quả
stats = pd.DataFrame({
    'Min': min_vals,
    'Mean': mean_vals,
    'Variance': var_vals,
    'Max': max_vals
})

print(stats)

                  Min         Mean      Variance       Max
knn_feature  0.050000     0.205761  9.032237e-03       0.8
gnb_feature  0.063813     0.247293  4.140036e-03       1.0
f3           0.000000  5255.438741  3.217241e+08  896040.0
f4           0.000000  4885.918741  2.542299e+08  621000.0
f5           0.000000  4841.508593  2.386421e+08  426529.0
f6           0.000000  5251.629963  3.173774e+08  528666.0


In [129]:
np.mean(X_train['knn_feature'])

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices